FROM node:16-alpine

# 為 Nuxt 等依賴安裝必要的構建工具
RUN apk add --no-cache build-base

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --production=false

COPY . .

RUN yarn build

CMD ["yarn", "start"]

EXPOSE 3001
