version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:eddie750905@db:5432/postgres
      API_COUNT_ENDPOINT: /api/device/running-count/
      API_DEVICE_ENDPOINT: /api/device/list
      API_TOKEN: 642d76b1ec903d3553e31f2962f0cf357f472362ac2b287f04a41b26bb93127b
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: eddie750905
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    networks:
      - my_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3001"
    depends_on:
      - backend
    networks:
      - my_network
networks:
  my_network: